name: CI
on: [push]
jobs:
  build:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Setup Chrome'
        uses: browser-actions/setup-chrome@latest

      - name: 'Install and Build'
        run: |
          yarn
          cd examples/vite-typescript-example
          yarn
          cd -
          yarn type-check
          yarn lint
          yarn build

      - name: 'Run Tests'
        run: CHROMIUM_BIN=$(which chrome) yarn test

      - name: 'Generate Documentation Website'
        run: yarn docs:generate

      - name: Deploy Documentation Website 🚀
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: documentation-website # The folder the action should deploy.
